Repository inductiva/inductiva, pull requests merged in 2024-03, with the labels that each got.

#1169 Added templating and configuring simulations to the how it works page
  docs/explore_api/configuring-simulators.md
  docs/explore_api/how_it_works.md
Labels: documentation

#1171 Fixed broken links in User Reference section
  docs/api_reference/computational_resources/elasticgroup_class.md
  docs/api_reference/computational_resources/machinegroup_class.md
  docs/api_reference/computational_resources/mpicluster_class.md
  docs/api_reference/faq.md
  docs/api_reference/troubleshooting.md
Labels: documentation

#1199 Add google analytics to docs
  .gitignore
  docs/conf.py
  docs/requirements.txt
Labels: documentation, enhancement

#1200 Create GitHub Pages deploy workflow for documentation site
  .github/workflows/build-docs.yml
Labels: documentation, enhancement

#1202 Fix typo in build command
  .github/workflows/build-docs.yml
Labels: bug

#1212 Fix email links
  docs/Home.md
  docs/api_reference/user_quotas.md
  docs/cli/storage.md
  docs/computational_resources/compute_janitor.md
  docs/installation.md
Labels: documentation

#1221 Update Inductiva logo on documentation website
  docs/_static/inductiva-logo-black.svg
  docs/_static/inductiva-logo-white.svg
Labels: documentation, enhancement

#1239 Fix mailto link typo
  docs/Home.md
Labels: bug, documentation

#1244 Set up OpenGraph protocol for documentation
  docs/_static/inductiva-social-banner.jpg
  docs/conf.py
  docs/requirements.txt
Labels: documentation, enhancement

#1264 Fix non-consecutive and starting heading warnings
  docs/api_reference/computational_resources/elasticgroup_class.md
  docs/api_reference/computational_resources/machinegroup_class.md
  docs/api_reference/computational_resources/mpicluster_class.md
  docs/cli/streaming-logs.md
  docs/how_to/manage-remote-storage.md
  docs/how_to/manage_and_retrieve_results.md
  docs/how_to/manage_computational_resources.md
  docs/how_to/manage_tasks.md
  docs/how_to/set-up-elastic-machine-group.md
  docs/simulators/GROMACS.md
  docs/simulators/OpenFOAM.md
  docs/simulators/SPlisHSPlasH.md
  docs/simulators/SWAN.md
  docs/simulators/SWASH.md
  docs/simulators/XBeach.md
Labels: bug, documentation

#1272 Exclude files from build
  docs/conf.py
Labels: bug, documentation
