Repository inductiva/inductiva, pull requests merged in 2024-06, with the labels that each got.

#1436 Fix broken tasks link on 'Track your Tasks' page
  docs/cli/tracking-tasks.md
Labels: bug, documentation

#1447 Update Inductiva package version from 0.5.0 to 0.7.1
  docs/get_started/installation.md
Labels: documentation, enhancement

#1484 Improved exception handling
  inductiva/logs/log.py
Labels: QA Needed
