Repository inductiva/inductiva, pull requests merged in 2024-04, with the labels that each got.

#1282 Run build-docs action also on push to development
  .github/workflows/build-docs.yml
Labels: bug, documentation

#1290 Fix documentation how to section link
  docs/Home.md
  docs/how_to/index.md
Labels: bug, documentation

#1291 Open external links on a new tab
  docs/conf.py
  docs/requirements.txt
Labels: documentation, enhancement

#1293 Set up nicholasphair/sphinx-action@7.0.0 in order to use myst-parser version pinned to commit hash
  .github/workflows/build-docs.yml
Labels: bug, documentation

#1299 Automatically generate sitemap.xml
  docs/conf.py
  docs/requirements.txt
Labels: documentation, enhancement

#1302 Get docs version from env var instead of git branch
  .github/workflows/build-docs.yml
  docs/conf.py
Labels: bug

#1314 Fix warnings on documentation
  docs/Home.md
  docs/conf.py
  docs/explore_api/templating.md
  docs/how_to/index.md
  docs/how_to/manage_tasks.md
  docs/simulators/Reef3D.md
  docs/simulators/index.md
  docs/uninstall_inductiva.md
Labels: documentation, enhancement

#1316 Handle warnings as errors
  .github/workflows/build-docs.yml
  docs/README.md
  docs/conf.py
Labels: documentation, enhancement

#1317 Fix development branch warnings
  .editorconfig
  docs/Home.md
  docs/api_reference/computational_resources/elasticgroup_class.md
  docs/api_reference/computational_resources/machinegroup_class.md
  docs/api_reference/computational_resources/mpicluster_class.md
  docs/cli/access-storage.md
  docs/cli/streaming-logs.md
  docs/conf.py
  docs/explore_api/configuring-simulators.md
  docs/explore_api/how_it_works.md
  docs/explore_api/tasks.md
  docs/explore_api/templating.md
  docs/how_to/index.md
  docs/how_to/manage-remote-storage.md
  docs/how_to/manage_and_retrieve_results.md
  docs/how_to/manage_computational_resources.md
  docs/how_to/manage_tasks.md
  docs/how_to/set-up-elastic-machine-group.md
  docs/index.md
  docs/simulators/GROMACS.md
  docs/simulators/OpenFAST.md
  docs/simulators/OpenFOAM.md
  docs/simulators/Reef3D.md
  docs/simulators/SCHISM.md
  docs/simulators/SPlisHSPlasH.md
  docs/simulators/SWAN.md
  docs/simulators/SWASH.md
  docs/simulators/XBeach.md
  docs/simulators/index.md
  docs/uninstall_inductiva.md
Labels: documentation, enhancement

#1322 Fine tune docs.inductiva.ai redirects
  .github/workflows/build-docs.yml
  docs/redirect.html
  docs/robots.txt
Labels: documentation, enhancement

#1336 Uncomment build-tutorials.yml actions
  .github/workflows/build-tutorials.yml
  tutorials/__init__.py
Labels: tutorials

#1337 Tweak tutorials build configuration
  .github/workflows/build-tutorials.yml
Labels: tutorials

#1351 Simplify deployment to staging
  .github/workflows/build-tutorials.yml
  .github/workflows/deploy-tutorials-to-staging.yml
Labels: enhancement, tutorials

#1353 Hide Synthetic Data Generation part 6
  tutorials/generating-synthetic-data/synthetic-data-generation-6.md
  tutorials/index.md
Labels: tutorials

#1354 Fix tutorials staging deployment actions
  .github/workflows/deploy-tutorials-to-staging.yml
  tutorials/redirect.html
Labels: bug, tutorials

#1363 First edit on tutorials.
  tutorials/index.md
Labels: tutorials

#1369 Fix typos and minor formatting issues
  tutorials/generating-synthetic-data/synthetic-data-generation-1.md
  tutorials/generating-synthetic-data/synthetic-data-generation-2.md
  tutorials/generating-synthetic-data/synthetic-data-generation-3.md
  tutorials/generating-synthetic-data/synthetic-data-generation-4.md
  tutorials/generating-synthetic-data/synthetic-data-generation-5.md
Labels: enhancement, tutorials
