Repository inductiva/inductiva, pull requests merged in 2024-01, with the labels that each got.

#948 Added Inductiva wiki files to docs
  docs/API-access-tokens.md
  docs/Home.md
  docs/Install.md
  docs/Machines.md
  docs/Running-multiple-simulations-in-parallel.md
  docs/Scenarios.md
  docs/Simulators.md
  docs/Start-simulating.md
  docs/Tasks.md
  docs/_Footer.md
  docs/_Sidebar.md
  docs/assets/splishsplash_input_file.png
  docs/assets/template.png
  docs/scenarios/Build-your-own-scenario.md
  docs/scenarios/Coastal-Area.md
  docs/scenarios/Fluid-Tank.md
  docs/scenarios/Protein-Solvation.md
  docs/scenarios/Wind-Tunnel.md
  docs/simulators/DualSPHysics.md
  docs/simulators/FDS.md
  docs/simulators/GROMACS.md
  docs/simulators/OpenFOAM.md
  docs/simulators/Reef3D.md
  docs/simulators/SPlisHSPlasH.md
  docs/simulators/SWASH.md
  docs/simulators/XBeach.md
  inductiva/__init__.py
Labels: documentation

#964 Update the documentation to download the generated output properly.
  docs/Tasks.md
  docs/_Footer.md
  docs/simulators/DualSPHysics.md
  docs/simulators/FDS.md
  docs/simulators/GROMACS.md
  docs/simulators/OpenFOAM.md
  docs/simulators/Reef3D.md
  docs/simulators/SPlisHSPlasH.md
  docs/simulators/SWASH.md
  docs/simulators/XBeach.md
Labels: documentation

#966 Fix code snippets and clean README's
  README.md
  docs/Install.md
  docs/Machines.md
  docs/Running-multiple-simulations-in-parallel.md
  docs/Simulators.md
  docs/Storage.md
  docs/Tasks.md
  docs/_Footer.md
  docs/_Sidebar.md
  docs/assets/splishsplash_input_file.png
  docs/assets/template.png
  docs/index.md
  docs/simulators/DualSPHysics.md
  docs/simulators/FDS.md
  docs/simulators/GROMACS.md
  docs/simulators/OpenFOAM.md
  docs/simulators/Reef3D.md
  docs/simulators/SPlisHSPlasH.md
  docs/simulators/SWASH.md
  docs/simulators/XBeach.md
  inductiva/resources/README.md
  inductiva/simulators/README.md
  inductiva/tasks/README.md
  inductiva/utils/files.py
Labels: documentation

#970 Removed reference to scenarios from the Install file
  docs/Install.md
Labels: documentation

#1000 Getting Started section
  docs/Getting Started.md
  docs/Install.md
  docs/Troubleshooting Guide.md
Labels: documentation, WIP

#983 First iteration on Inductiva's Home page
  docs/Home.md
Labels: documentation, WIP

#1019 Getting Started final iteration
  docs/Getting Started.md
  docs/Troubleshooting Guide.md
Labels: documentation, help wanted
